import {q} from './db.js'; import {configured,searchOffers} from './francetravail.js'; import {enrichCompany,employeeCount} from './sirene.js'; import {score} from './matching.js';
const DEPTS=new Set(['75','77','78','91','92','93','94','95']);
function deptFromPostcode(p=''){return p.slice(0,2)==='20'?'2A':p.slice(0,2);}
function isRelevant(o){const t=(o.intitule+' '+(o.description||'')).toLowerCase(); return /(maintenance industrielle|technicien de maintenance|electrotechnicien|électrotechnicien|electromecanicien|électromécanicien|technicien sav)/i.test(t)&&!/(informatique|it support|automobile|batiment uniquement)/i.test(t);}
export async function syncFranceTravail(){const run=(await q(`INSERT INTO sync_runs(source,status) VALUES('France Travail','running') RETURNING id`)).rows[0].id; const stats={offers:0,companies:0,rejected:0,matches:0}; try{if(!configured())throw new Error('France Travail non configuré: renseignez FT_CLIENT_ID et FT_CLIENT_SECRET dans .env'); const data=await searchOffers(); for(const o of (data.resultats||[])){const postcode=o.lieuTravail?.codePostal||''; const dept=deptFromPostcode(postcode); if(!DEPTS.has(dept)||!isRelevant(o)){stats.rejected++;continue;} const ent=o.entreprise||{}; const name=ent.nom||'Entreprise non renseignée';function isRecruitmentIntermediary(name=''){
  return /(randstad|nextep|adecco|manpower|synergie|proman|page personnel|pagegroup|hays|kelly|expectra|crit|start people|interaction|partnaire|supplay|actual|temporis|aquila rh|ras interim|iziwork)/i.test(name);
} let company=(await q('SELECT * FROM companies WHERE siret=$1 OR (siret IS NULL AND name=$2) LIMIT 1',[ent.siret||null,name])).rows[0]; if(!company){let s=null; try{s=await enrichCompany(name,postcode)}catch{} const ec=employeeCount(s); company=(await q(`INSERT INTO companies(name,siret,siren,address,postcode,city,department,website,employee_count,employee_source,commercial_score,source,raw) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'France Travail',$12) RETURNING *`,[name,ent.siret||s?.siren||null,s?.siren||null,s?.siege?.adresse||null,postcode,o.lieuTravail?.commune||null,dept,ent.url||null,ec,ec!=null?'SIRENE':null,ec!=null&&ec<=40?Math.min(100,70+(ec<20?20:10)):0,JSON.stringify(ent)] )).rows[0]; stats.companies++;} if(company.employee_count!=null&&company.employee_count>40)continue; await q(`INSERT INTO jobs(source,source_id,title,company_id,description,location,postcode,department,contract_type,contract_duration,salary_text,schedule,experience,skills,url,published_at,updated_source_at,raw) VALUES('France Travail',$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) ON CONFLICT(source,source_id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,company_id=EXCLUDED.company_id,salary_text=EXCLUDED.salary_text,url=EXCLUDED.url,updated_source_at=EXCLUDED.updated_source_at,raw=EXCLUDED.raw,status='active',updated_at=now()`,[o.id,o.intitule,company.id,o.description||'',o.lieuTravail?.libelle||'',postcode,dept,o.typeContrat||'',o.dureeTravailLibelle||'',o.salaire?.libelle||'',o.horaireTravail||'',o.experienceLibelle||'',o.competences?.map(x=>x.libelle).join(', ')||'',o.origineOffre?.urlOrigine||o.contact?.urlPostulation||'',o.dateCreation||null,o.dateActualisation||null,JSON.stringify(o)]); stats.offers++;}
 const jobs=(await q(`SELECT j.*,c.employee_count FROM jobs j LEFT JOIN companies c ON c.id=j.company_id WHERE j.status='active' AND (c.employee_count IS NULL OR c.employee_count<=40) LIMIT 300`)).rows; const cand=(await q(`SELECT * FROM candidates WHERE active_search=true LIMIT 300`)).rows; for(const j of jobs)for(const c of cand){const m=score(j,c); if(m.score>=Number(process.env.MATCH_ALERT_THRESHOLD||85)){const r=await q(`INSERT INTO matches(job_id,candidate_id,score,reasons) VALUES($1,$2,$3,$4) ON CONFLICT(job_id,candidate_id) DO UPDATE SET score=EXCLUDED.score,reasons=EXCLUDED.reasons RETURNING id`,[j.id,c.id,m.score,JSON.stringify(m.reasons)]); if(r.rows.length) {await q(`INSERT INTO alerts(type,job_id,candidate_id,score,message) VALUES('match',$1,$2,$3,$4)`,[j.id,c.id,m.score,`Match ${m.score}%: ${j.title}`]); stats.matches++;}}}
 await q(`UPDATE sync_runs SET finished_at=now(),status='success',stats=$1 WHERE id=$2`,[JSON.stringify(stats),run]); return stats;
 }catch(e){await q(`UPDATE sync_runs SET finished_at=now(),status='error',error=$1 WHERE id=$2`,[e.message,run]);throw e;}}
